In [5]:
import pandas as pd
from pathlib import Path
import os
sil_dir = Path("../../data/silver")
print(os.getcwd())
for file in sil_dir.glob("*.parquet"):
    df = pd.read_parquet(file)
    display(df.head())

/home/seb/cours/hackaton/src/scripts

,date,num_poste,nom_usuel,latitude,longitude,altitude,tx,q_hom
0,1959-01-01,10057001,BOUY-SUR-ORVIN,48.44,3.505,102,5.5,1
1,1959-02-01,10057001,BOUY-SUR-ORVIN,48.44,3.505,102,7.8,1
2,1959-03-01,10057001,BOUY-SUR-ORVIN,48.44,3.505,102,12.7,1
3,1959-04-01,10057001,BOUY-SUR-ORVIN,48.44,3.505,102,15.0,1
4,1959-05-01,10057001,BOUY-SUR-ORVIN,48.44,3.505,102,20.6,1

,date,num_poste,nom_usuel,latitude,longitude,altitude,tn,q_hom
0,1959-01-01,10057001,BOUY-SUR-ORVIN,48.44,3.505,102,-0.6,1
1,1959-02-01,10057001,BOUY-SUR-ORVIN,48.44,3.505,102,-1.4,1
2,1959-03-01,10057001,BOUY-SUR-ORVIN,48.44,3.505,102,2.9,1
3,1959-04-01,10057001,BOUY-SUR-ORVIN,48.44,3.505,102,4.5,1
4,1959-05-01,10057001,BOUY-SUR-ORVIN,48.44,3.505,102,7.7,1

,date,num_poste,nom_usuel,latitude,longitude,altitude,rr,q_hom
0,1955-01-01,10030001,TROYES-BARBEREY,48.325,4.02,112,123.8,1
1,1955-02-01,10030001,TROYES-BARBEREY,48.325,4.02,112,90.8,1
2,1955-03-01,10030001,TROYES-BARBEREY,48.325,4.02,112,15.5,1
3,1955-04-01,10030001,TROYES-BARBEREY,48.325,4.02,112,4.4,1
4,1955-05-01,10030001,TROYES-BARBEREY,48.325,4.02,112,29.6,1