In [3]:
import pandas as pd
import os
import numpy as np

GOLD_DIR = "../../../data/gold"

for file in os.listdir(GOLD_DIR):
    if not file.endswith(".parquet"):
        continue
    print(file)
    df = pd.read_parquet(os.path.join(GOLD_DIR, file))
    display(df.head())

incendies.parquet

,annee,numero,departement,code_insee,commune,date_alerte,surface_totale_m2,surface_foret_m2,surface_maquis_m2,surface_autres_naturelles_m2,...,surface_non_boisee_artificielle_m2,surface_non_boisee_m2,precision_surfaces,type_peuplement,nature,deces_ou_batiments,nb_deces,nb_batiments_detruits,nb_batiments_partiels,precision_donnee
0,1973,8,06,06060,Falicon,1973-01-09 13:50:00,10000,4700.0,4800.0,0.0,...,NaN,500.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1,1973,1871,83,83038,Châteaudouble,1973-01-28 13:25:00,30000,14100.0,14400.0,0.0,...,NaN,1500.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN
2,1973,1872,83,83078,Moissac-Bellevue,1973-01-29 11:15:00,6000,2820.0,2880.0,0.0,...,NaN,300.0,NaN,1.0,Involontaire (travaux),NaN,NaN,NaN,NaN,NaN
3,1973,1639,34,34163,Montarnaud,1973-01-29 13:00:00,100000,47000.0,48000.0,0.0,...,NaN,5000.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
4,1973,9,06,06012,Beausoleil,1973-01-29 15:00:00,40000,18800.0,19200.0,0.0,...,NaN,2000.0,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN

ges_citepa.parquet

   annee                 substance      valeur      unite  utcatf_inclus
0   1990  Dioxyde de carbone (CO2)  399.810741  Mt CO2/an          False
1   1991  Dioxyde de carbone (CO2)  424.480081  Mt CO2/an          False
2   1992  Dioxyde de carbone (CO2)  414.106608  Mt CO2/an          False
3   1993  Dioxyde de carbone (CO2)  394.901901  Mt CO2/an          False
4   1994  Dioxyde de carbone (CO2)  388.180589  Mt CO2/an          False

ges_communes.parquet

,annee,geocode_commune,libelle_commune,secteur,valeur
0,2016,01001,L'Abergement-Clémenciat,Agriculture,3857.574837
1,2016,01001,L'Abergement-Clémenciat,Déchets,24.414205
2,2016,01001,L'Abergement-Clémenciat,Energie,0.000000
3,2016,01001,L'Abergement-Clémenciat,Industrie hors Energie,2.050853
4,2016,01001,L'Abergement-Clémenciat,Résidentiel,350.683419

climat_metropole.parquet

,date,num_poste,nom_usuel,latitude,longitude,altitude,tn,q_hom_tn,tx,q_hom_tx,rr,q_hom_rr
0,1955-01-01,10030001,TROYES-BARBEREY,48.325,4.02,112.0,NaN,NaN,NaN,NaN,123.8,1.0
1,1955-02-01,10030001,TROYES-BARBEREY,48.325,4.02,112.0,NaN,NaN,NaN,NaN,90.8,1.0
2,1955-03-01,10030001,TROYES-BARBEREY,48.325,4.02,112.0,NaN,NaN,NaN,NaN,15.5,1.0
3,1955-04-01,10030001,TROYES-BARBEREY,48.325,4.02,112.0,NaN,NaN,NaN,NaN,4.4,1.0
4,1955-05-01,10030001,TROYES-BARBEREY,48.325,4.02,112.0,NaN,NaN,NaN,NaN,29.6,1.0

cata.parquet

,code_insee,code_dept,commune,peril,date_debut,date_fin,duree_jours
0,1053,1,Bourg-en-Bresse,Inondations et coulées de boue,1982-12-08,1982-12-31,23
1,1074,1,Chalamont,Inondations et coulées de boue,1982-12-08,1982-12-31,23
2,1016,1,Arbigny,Inondations et coulées de boue,1983-04-09,1983-04-15,6
3,1023,1,Asnières-sur-Saône,Inondations et coulées de boue,1983-04-09,1983-04-15,6
4,1057,1,Boz,Inondations et coulées de boue,1983-04-09,1983-04-15,6

empreinte_carbone.parquet

,annee,empreinte_par_personne_tco2eq,empreinte_totale_mtco2eq,emissions_directes_menages_mtco2eq
0,1990,12.068,702.062428,130.420389
1,1991,12.028,703.138442,138.834628
2,1992,11.791,692.607168,140.393552
3,1993,10.952,645.992235,138.802212
4,1994,10.828,641.012151,134.935370

In [ ]:
j1 = pd.read_parquet(os.path.join(d